name: Build luci-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ar tar gzip

      - name: Build IPK package
        run: |
          APP_NAME="luci-app-kidcontrol"
          VERSION="1.0-1"

          mkdir -p build/CONTROL
          mkdir -p build/usr/lib/lua/luci

          cat > build/CONTROL/control <<EOF
Package: $APP_NAME
Version: $VERSION
Depends: nftables
Architecture: all
Maintainer: HolyHBC
Section: luci
Priority: optional
Description: LuCI support for Kid Control
EOF

          if [ -d "$APP_NAME/luasrc" ]; then
            cp -r $APP_NAME/luasrc/* build/usr/lib/lua/luci/
          fi
          if [ -d "$APP_NAME/root" ]; then
            cp -r $APP_NAME/root/* build/
          fi

          cd build
          tar --numeric-owner --group=0 --owner=0 -czf ../data.tar.gz $(ls | grep -v CONTROL)
          cd CONTROL
          tar --numeric-owner --group=0 --owner=0 -czf ../../control.tar.gz control
          cd ../..

          echo -n "2.0" > debian-binary
          ar r $APP_NAME.ipk debian-binary control.tar.gz data.tar.gz

          mkdir -p output
          mv $APP_NAME.ipk output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-ipk
          path: output/*.ipk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.ipk
          tag_name: v${{ github.run_number }}
          name: "Build #${{ github.run_number }}"
          body: |
            自动构建的 LuCI 应用安装包。
            - 包名: luci-app-kidcontrol
            - 版本: 1.0-1
            - 构建编号: ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify IPK format
        run: |
          FILE=$(ls output/*.ipk)
          echo "✅ Created IPK: $FILE"
          ar t "$FILE"
          echo ""
          echo "File size:"
          ls -lh "$FILE"
