name: Build on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build IPK
      run: |
        # 构建步骤同上
        mkdir -p ipk-build/CONTROL
        echo "Package: luci-app-kidcontrol" > ipk-build/CONTROL/control
        echo "Version: ${GITHUB_REF#refs/tags/}" >> ipk-build/CONTROL/control
        echo "Architecture: all" >> ipk-build/CONTROL/control
        echo "Description: LuCI support for Kid Control" >> ipk-build/CONTROL/control
        
        if [ -d "luasrc" ]; then
          mkdir -p ipk-build/usr/lib/lua/luci
          cp -r luasrc/* ipk-build/usr/lib/lua/luci/
        fi
        
        if [ -d "root" ]; then
          cp -r root/* ipk-build/
        fi
        
        cd ipk-build
        tar -czf ../control.tar.gz CONTROL/
        find . -path ./CONTROL -prune -o -type f -print | tar -czf ../data.tar.gz -T -
        echo "2.0" > ../debian-binary
        cd ..
        ar r luci-app-kidcontrol.ipk debian-binary control.tar.gz data.tar.gz
        rm -f control.tar.gz data.tar.gz debian-binary
        rm -rf ipk-build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        files: luci-app-kidcontrol.ipk
        body: |
          Auto-built luci-app-kidcontrol
          Version: ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
