name: Build luci-app-kidcontrol

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ar tar gzip

    - name: Create proper IPK structure
      run: |
        # 创建标准的IPK结构
        mkdir -p ipk-build/CONTROL
        mkdir -p ipk-build/usr/lib/lua/luci
        
        # 创建正确的control文件格式
        cat > ipk-build/CONTROL/control << 'EOL'
Package: luci-app-kidcontrol
Version: 1.0-1
Depends: nftables
Architecture: all
Maintainer: HolyHBC
Section: luci
Priority: optional
Description: LuCI support for Kid Control
EOL

        # 复制luasrc文件
        if [ -d "luci-app-kidcontrol/luasrc" ]; then
          cp -r luci-app-kidcontrol/luasrc/* ipk-build/usr/lib/lua/luci/
          echo "✅ Copied luasrc files"
        fi

        # 复制root文件
        if [ -d "luci-app-kidcontrol/root" ]; then
          cp -r luci-app-kidcontrol/root/* ipk-build/
          echo "✅ Copied root files"
        fi

        # 显示文件结构
        echo "File structure:"
        find ipk-build -type f

    - name: Create valid IPK package
      run: |
        # 进入构建目录
        cd ipk-build
        
        # 创建data.tar.gz（包含所有文件）
        tar -czf ../data.tar.gz ./*
        
        # 创建control.tar.gz（只包含CONTROL目录）
        tar -czf ../control.tar.gz ./CONTROL/
        
        # 创建debian-binary
        echo "2.0" > ../debian-binary
        
        # 回到上级目录
        cd ..
        
        # 使用正确的ar命令格式创建IPK
        ar rcs luci-app-kidcontrol.ipk debian-binary control.tar.gz data.tar.gz
        
        # 检查IPK文件
        echo "✅ IPK file created:"
        ls -la luci-app-kidcontrol.ipk
        echo ""
        echo "IPK contents:"
        ar t luci-app-kidcontrol.ipk

        # 创建输出目录
        mkdir -p output
        cp luci-app-kidcontrol.ipk output/
        
        # 清理
        rm -f debian-binary control.tar.gz data.tar.gz
        rm -rf ipk-build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-kidcontrol-valid-ipk
        path: output/luci-app-kidcontrol.ipk

    - name: Verify IPK format
      run: |
        # 验证IPK格式
        echo "Verifying IPK format..."
        ar t output/luci-app-kidcontrol.ipk
        echo ""
        echo "File size:"
        ls -la output/luci-app-kidcontrol.ipk
