name: Build and Release luci-app-kidcontrol

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build IPK package
      run: |
        # 创建必要的目录结构
        mkdir -p ipk-build/CONTROL
        
        # 创建control文件
        echo "Package: luci-app-kidcontrol" > ipk-build/CONTROL/control
        echo "Version: ${{ github.event.release.tag_name }}" >> ipk-build/CONTROL/control
        echo "Architecture: all" >> ipk-build/CONTROL/control
        echo "Description: LuCI support for Kid Control" >> ipk-build/CONTROL/control

        # 复制luasrc目录
        if [ -d "luasrc" ]; then
          mkdir -p ipk-build/usr/lib/lua/luci
          cp -r luasrc/* ipk-build/usr/lib/lua/luci/
          echo "✅ Copied luasrc"
        fi

        # 复制root目录（如果有）
        if [ -d "root" ]; then
          cp -r root/* ipk-build/
          echo "✅ Copied root"
        fi

        # 构建IPK
        cd ipk-build
        tar -czf ../control.tar.gz CONTROL/
        find . -path ./CONTROL -prune -o -type f -print | tar -czf ../data.tar.gz -T -
        echo "2.0" > ../debian-binary
        cd ..
        ar r luci-app-kidcontrol.ipk debian-binary control.tar.gz data.tar.gz
        
        # 清理临时文件
        rm -f control.tar.gz data.tar.gz debian-binary
        rm -rf ipk-build
        
        echo "✅ IPK built successfully"
        ls -la *.ipk

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: luci-app-kidcontrol.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
